import { createContext, useContext, useState } from 'react'

export const translations = {
  fr: {
    welcome: 'Bienvenue sur', appName: 'MoodTracker !',
    welcomeSub: 'Ton espace pour suivre comment tu te sens chaque jour.',
    login: 'Se connecter', register: "S'inscrire",
    email: 'Email', password: 'Mot de passe',
    loginBtn: 'Je vais aller mieux ❤️', back: '← Retour',
    firstname: 'Prénom', confirmPwd: 'Confirmer mot de passe',
    chooseLanguage: 'Choisir la langue / Choose language',
    moodQuestion: 'Comment tu te sens\naujourd\'hui ?',
    moodHint: 'Sélectionne ton humeur ↑',
    moodHappy: 'Tu es au top aujourd\'hui !',
    moodOk: 'Pas mal, ça va à peu près !',
    moodSad: 'Je suis là pour t\'écouter.',
    continueBtn: 'Continuer →', moreTellBtn: 'En dire plus', confideBtn: 'Me confier →',
    tooDayHappy: 'Aujourd\'hui tu es au top',
    alwaysCase: 'c\'est toujours le cas !',
    wantMoreInfo: 'tu veux m\'en dire plus ?',
    yes: 'Oui', no: 'Non',
    listeningTitle: 'Je t\'écoute', journalPH: 'Aujourd\'hui je...',
    tags: ['Sorti·e', 'Me suis fait plaisir', 'Mal dormi·e', 'Fait du sport', 'Au cinéma', 'Bonne nouvelle'],
    thanksTitle: 'Merci pour ton retour',
    thanksSub: 'Tu peux toujours modifier ce moment dans le calendrier !',
    seeCalendar: 'Voir le calendrier',
    calendarTitle: 'Calendrier',
    months: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    days: ['L','M','M','J','V','S','D'],
    legendGood: '🟢 Bien', legendOk: '🟡 Moyen', legendHard: '🔴 Difficile',
    calHint: 'Clique sur un jour pour voir le détail',
    editEntry: '✏️ Modifier', addEntry: '+ Ajouter',
    noComment: 'Aucun commentaire', notLogged: 'non renseigné', close: 'Fermer',
    editDay: 'Modifier le jour', addComment: 'Ajouter un commentaire...',
    cancel: 'Annuler', save: 'Sauvegarder',
    sleepLabel: 'Heures de sommeil', sleepQuestion: 'Tu as bien dormi ?', sleepSub: 'Combien d\'heures as-tu dormi cette nuit ?', skipBtn: 'Passer', avgSleep: 'Sommeil moyen',
    statsTitle: 'Statistiques', daysTracked: 'Jours suivis',
    topMood: 'Humeur fréquente', positiveDays: 'Jours positifs', streak: 'Streak 🔥',
    thisWeek: 'Cette semaine',
    daysShort: ['Lun','Mar','Mer','Jeu','Ven','Sam','Auj'],
    moodLabel: 'Humeur',
    sleepMoodChart: '😴 Sommeil & humeur',
    sleepCorrelationPos: '✨ Quand tu dors plus (≥7h), ton humeur est meilleure. Continue comme ça !',
    sleepCorrelationNeg: '🤔 Curieux — ton humeur semble meilleure avec moins de sommeil ce mois-ci.',
    sleepCorrelationNeutral: '📊 Pas de lien clair entre ton sommeil et ton humeur ce mois-ci.',
    chartTitle: 'Graphique', noData: '📋 Pas assez de données ce mois-ci.',
    trendHigh: '📊 Humeur globalement élevée ce mois-ci.',
    trendMid: '📊 Humeur plutôt stable et dans la moyenne.',
    trendLow: '📊 Quelques hauts et bas ce mois-ci.',
    trendHard: '📊 Mois difficile dans l\'ensemble.',
    trendUp: '↗ En progression sur la période.',
    trendDown: '↘ En baisse sur la période.',
    accountTitle: 'Mon compte', personalInfo: 'Informations personnelles',
    preferences: 'Préférences', privacy: 'Confidentialité',
    editLabel: 'Modifier', pwdLabel: 'Mot de passe',
    notifLabel: 'Notifications', dailyReminder: 'Rappel quotidien',
    reminderTime: 'Heure de rappel', soundLabel: 'Sons', soundEffects: 'Effets sonores',
    langLabel: 'Langue', dataLabel: 'Données', exportData: 'Exporter mes données',
    historyLabel: 'Historique', deleteHistory: "Supprimer l'historique",
    clearLabel: 'Effacer', deleteAccount: '🗑 Supprimer mon compte',
    deleteTitle: 'Supprimer mon compte ?',
    deleteBody: 'Cette action est irréversible. Toutes tes données seront perdues.',
    deleteConfirm: 'Supprimer',
    navMood: 'Humeur du jour', navCalendar: 'Calendrier', navStats: 'Statistiques',
    navChart: 'Graphique', navAccount: 'Mon compte', navLogout: 'Se déconnecter',
    langValue: 'Français 🇫🇷',
    pwdPlaceholders: ['Mot de passe actuel', 'Nouveau mot de passe', 'Confirmer'],
    badgesTitle: 'Mes badges', avatarTitle: 'Mon avatar',
    badgeStarter:    '🌱 Débutant',    badgeStarterDesc:    'Bienvenue dans l\'aventure !',
    badgeStreak3:    '🔥 En route',    badgeStreak3Desc:    '3 jours consécutifs',
    badgeStreak7:    '⚡ Régulier',    badgeStreak7Desc:    '7 jours consécutifs',
    badgeStreak30:   '💎 Engagé·e',   badgeStreak30Desc:   '30 jours consécutifs',
    badgeEntries10:  '🦉 Observateur·rice', badgeEntries10Desc: '10 entrées enregistrées',
    badgeEntries50:  '🌟 Vétéran·e', badgeEntries50Desc:  '50 entrées enregistrées',
    badgeEntries100: '🏆 Légende',    badgeEntries100Desc: '100 entrées enregistrées',
    badgeLocked: 'Verrouillé',
    shareBtn: 'Partager', shareBadgeText: (badge, app) => `Je viens de débloquer le badge ${badge} sur ${app} !`,
    dailyQuotes: [
      'Prendre soin de soi, c\'est déjà beaucoup.',
      'Chaque jour compte, même les gris.',
      'Tu n\'as pas à aller bien tout le temps.',
      'Observer ses émotions, c\'est déjà avancer.',
      'La constance vaut plus que la perfection.',
      'Être là, présent·e, c\'est suffisant.',
      'Ton ressenti est valide, quoi qu\'il soit.',
    ],
  },
  en: {
    welcome: 'Welcome to', appName: 'MoodTracker!',
    welcomeSub: 'Your space to track how you feel every day.',
    login: 'Log in', register: 'Sign up',
    email: 'Email', password: 'Password',
    loginBtn: "I'll feel better ❤️", back: '← Back',
    firstname: 'First name', confirmPwd: 'Confirm password',
    chooseLanguage: 'Choose language / Choisir la langue',
    moodQuestion: 'How are you\nfeeling today?',
    moodHint: 'Select your mood ↑',
    moodHappy: "You're super happy today!",
    moodOk: 'Not bad, things are okay!',
    moodSad: "I'm here to listen.",
    continueBtn: 'Continue →', moreTellBtn: 'Tell me more', confideBtn: 'Open up →',
    tooDayHappy: "You're so happy today",
    alwaysCase: 'as always!', wantMoreInfo: 'want to tell me more?',
    yes: 'Yes', no: 'No',
    listeningTitle: "I'm listening", journalPH: 'Today I...',
    tags: ['Went out', 'Treated myself', 'Slept badly', 'Exercised', 'Went to cinema', 'Good news'],
    thanksTitle: 'Thanks for sharing',
    thanksSub: 'You can always edit this in the calendar!',
    seeCalendar: 'View calendar', calendarTitle: 'Calendar',
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    days: ['M','T','W','T','F','S','S'],
    legendGood: '🟢 Good', legendOk: '🟡 Okay', legendHard: '🔴 Hard',
    calHint: 'Tap a day to see details',
    editEntry: '✏️ Edit', addEntry: '+ Add',
    noComment: 'No comment', notLogged: 'not logged', close: 'Close',
    editDay: 'Edit day', addComment: 'Add a comment...',
    cancel: 'Cancel', save: 'Save',
    sleepLabel: 'Hours of sleep', sleepQuestion: 'Did you sleep well?', sleepSub: 'How many hours did you sleep last night?', skipBtn: 'Skip', avgSleep: 'Avg sleep',
    statsTitle: 'Statistics', daysTracked: 'Days tracked',
    topMood: 'Top mood', positiveDays: 'Positive days', streak: 'Streak 🔥',
    thisWeek: 'This week',
    daysShort: ['Mon','Tue','Wed','Thu','Fri','Sat','Tod'],
    moodLabel: 'Mood',
    sleepMoodChart: '😴 Sleep & mood',
    sleepCorrelationPos: '✨ When you sleep more (≥7h), your mood is better. Keep it up!',
    sleepCorrelationNeg: '🤔 Interesting — your mood seems better with less sleep this month.',
    sleepCorrelationNeutral: '📊 No clear link between sleep and mood this month.',
    chartTitle: 'Chart', noData: '📋 Not enough data this month.',
    trendHigh: '📊 Generally high mood this month.',
    trendMid: '📊 Fairly stable mood this month.',
    trendLow: '📊 Some ups and downs this month.',
    trendHard: '📊 A difficult month overall.',
    trendUp: '↗ On the rise over the period.',
    trendDown: '↘ Declining over the period.',
    accountTitle: 'My account', personalInfo: 'Personal info',
    preferences: 'Preferences', privacy: 'Privacy',
    editLabel: 'Edit', pwdLabel: 'Password',
    notifLabel: 'Notifications', dailyReminder: 'Daily reminder',
    reminderTime: 'Reminder time', soundLabel: 'Sounds', soundEffects: 'Sound effects',
    langLabel: 'Language', dataLabel: 'Data', exportData: 'Export my data',
    historyLabel: 'History', deleteHistory: 'Delete history',
    clearLabel: 'Clear', deleteAccount: '🗑 Delete my account',
    deleteTitle: 'Delete my account?',
    deleteBody: 'This action is irreversible. All your data will be lost.',
    deleteConfirm: 'Delete',
    navMood: "Today's mood", navCalendar: 'Calendar', navStats: 'Statistics',
    navChart: 'Chart', navAccount: 'My account', navLogout: 'Log out',
    langValue: 'English 🇬🇧',
    pwdPlaceholders: ['Current password', 'New password', 'Confirm'],
    badgesTitle: 'My badges', avatarTitle: 'My avatar',
    badgeStarter:    '🌱 Beginner',   badgeStarterDesc:    'Welcome to the journey!',
    badgeStreak3:    '🔥 On a roll',  badgeStreak3Desc:    '3 days in a row',
    badgeStreak7:    '⚡ Consistent', badgeStreak7Desc:    '7 days in a row',
    badgeStreak30:   '💎 Committed',  badgeStreak30Desc:   '30 days in a row',
    badgeEntries10:  '🦉 Observer',   badgeEntries10Desc:  '10 entries logged',
    badgeEntries50:  '🌟 Veteran',    badgeEntries50Desc:  '50 entries logged',
    badgeEntries100: '🏆 Legend',     badgeEntries100Desc: '100 entries logged',
    badgeLocked: 'Locked',
    shareBtn: 'Share', shareBadgeText: (badge, app) => `I just unlocked the ${badge} badge on ${app}!`,
    dailyQuotes: [
      'Taking care of yourself is already a lot.',
      'Every day counts, even the grey ones.',
      'You don\'t have to be okay all the time.',
      'Noticing your emotions is already progress.',
      'Consistency matters more than perfection.',
      'Being present is enough.',
      'Whatever you feel is valid.',
    ],
  }
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr')
  const t = (key) => translations[lang][key] ?? key
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
